import sys
import os

# Ensure agents directory is in path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from agents import PsychologicalAgent, IntelAgent, StrategyAgent
from celery import shared_task
import models, database

@shared_task(name="run_agent_analysis")
def run_agent_analysis(case_id: int):
    db = next(database.get_db())
    case = db.query(models.Case).filter(models.Case.id == case_id).first()
    msg = db.query(models.Message).filter(models.Message.id == case.initial_message_id).first()
    
    agent_a = PsychologicalAgent()
    agent_b = IntelAgent()
    agent_c = StrategyAgent()

    # Analysis A
    res_a = agent_a.analyze(msg.text)

    # Analysis B
    res_b = agent_b.analyze(msg.text)

    # Consolidation C
    res_c = agent_c.analyze(f"Analysis A: {res_a}\\nAnalysis B: {res_b}")

    case.agent_analysis = {
        "agent_a": res_a,
        "agent_b": res_b,
        "agent_c": res_c
    }
    case.status = "analyzed"
    db.commit()
    
    # Generate PDF Report
    from reporting.pdf_generator import generate_pdf_report
    from reporting.email_sender import send_email_with_pdf
    
    report_path = f"data/case_{case.id}.pdf"
    case_data = {
        "id": case.id,
        "summary": "Case generated by high risk scoring and agent analysis.",
        "risk_score": case.risk_score,
        "status": case.status,
        "user_hash": case.user_hash,
        "agent_analysis": case.agent_analysis
    }
    generate_pdf_report(case_data, report_path)
    
    # Send Email
    send_email_with_pdf(case.id, case.risk_score, report_path)

